### ISSUE TITLE
Check if final marking is exported in Petri net export

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/2.1#6]
Check if final marking is exported in Petri net export

**Comment by TaXxER** [comment]
I happened to have exported a Petri net in RapidProM yesterday. The final marking is not exported.

**Comment by s-j-v-zelst** [comment]
I traced the problem.
This was due to an old Petri nets package.
The newest Petri nets package does export final markings.
I have updated the rapidprom-libraries for version 4.0.0
